runtime: custom
env: flex

runtime_config:
  python_version: 3
env_variables:
  CUSTOMER_ID: "8625928079"
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 1
readiness_check:
  app_start_timeout_sec: 1800
resources:
  cpu: 1
  memory_gb: 6
  disk_size_gb: 12
